apiVersion: v1
kind: Secret
metadata:
  name: {{ include "job-tracker.fullname" . }}-secret
  labels:
    {{- include "job-tracker.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  REDIS_HOST: {{ .Values.secrets.REDIS_HOST | b64enc | quote }}
  REDIS_PORT: {{ .Values.secrets.REDIS_PORT | b64enc | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secrets.JWT_ACCESS_SECRET | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.JWT_REFRESH_SECRET | b64enc | quote }}
